/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/evtepDlGXos
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { IBM_Plex_Sans } from 'next/font/google'
import { Arimo } from 'next/font/google'

ibm_plex_sans({
  subsets: ['latin'],
  display: 'swap',
})

arimo({
  subsets: ['latin'],
  display: 'swap',
})


**/
import Header from "@/components/HomePage/Header";
import Link from "next/link";
import {Template} from '../../components/templates'
export default function () {
  return (
    <>
      {" "}
      <Header />
      <main
        key="1"
        className="w-full mx-auto px-4 py-12 md:px-6 lg:py-16 bg-gray-950 dark:bg-gray-950"
      >
        <div className="flex flex-col items-center text-center space-y-4 mb-8">
          <h1 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl mt-20 text-gray-50 dark:text-gray-50">
            Explore Our Themes
          </h1>
          <p className="max-w-[700px] text-gray-400 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
            Find the perfect theme for your project and get started today.
          </p>
        </div>
        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6 mx-24">
         <Template/>
         <Template/>
         <Template/>
         <Template/>
         <Template/>
         <Template/>

       
         
        </div>
      </main>
    </>
  );
}
